apiVersion: v1
kind: Pod
metadata:
  name: fed-int
spec:
  containers:
    - name: fed-int
      image: 'containers.cisco.com/zidlu/fed-int:latest'
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 1
          memory: 1Gi
      imagePullPolicy: Always
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsUser: 0
  restartPolicy: OnFailure

